modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "bikesarepain"
version = "${version}"
displayName = "BikesArePain"
authors = "Kadmuffin"
description = "Adds bikes to the game and allows you to use real fitness bikes to move in-game. Uses JSerialComm under the Apache 2.0 License under the hood."

#logoFile = ""

[[dependencies.bikesarepain]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "geckolib"
type = "required"
versionRange = "[4.5.0,5.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.5.0,4.0.0)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "bikesarepain.mixins.json"
