modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/kadmuffin/bikesarepain-mod/issues"
license = "MIT"

[[mods]]
modId = "bikesarepain"
version = "${version}"
displayName = "Bikes Are Pain"
authors = "Kadmuffin"
description = "[ALPHA] Adds a bike to the game and allows you to use a fitness bike to move in-game. Uses JSerialComm (Apache 2.0 License) under the hood."

#logoFile = ""

[[dependencies.bikesarepain]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "geckolib"
type = "required"
versionRange = "[4.7.0,5.0.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "yet_another_config_lib_v3"
type = "required"
versionRange = "[3.6.0,4.0.0)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config = "bikesarepain.mixins.json"
