modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "bikesarepain"
version = "${version}"
displayName = "BikesArePain"
authors = "Kadmuffin"
description = '''

'''
#logoFile = ""

[[dependencies.bikesarepain]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "architectury"
type = "required"
versionRange = "[13.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.bikesarepain]]
modId = "geckolib"
type = "required"
versionRange = "[4.5.0,5.0.0)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "bikesarepain.mixins.json"
